CREATE TABLE IF NOT EXISTS seguimientos
(
    id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	fecha date,
    name text NOT NULL CHECK (name <> ''),
    motivo text NOT NULL CHECK (name <> ''),
	estado text NOT NULL CHECK (name <> ''),
	orientador text NOT NULL CHECK (name <> '')
);

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-08-15', 'Ricardo Enrique Bochini', 'Pedagogía', 'Citadx', 'Julio Grondona');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-08-15', 'Carlos Alberto Enrique', 'Salud Mental', 'En Proceso', 'Julio Grondona');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-08-16', 'Ricardo Omar Giusti', 'Discapacidad','Sin Estado', 'Julio Grondona');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-08-16', 'Claudio Oscar Marangoni', 'Re-orienacion vocacional','Citadx', 'Julio Grondona');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-08-20', 'Jorge Luis Burruchaga', 'Pedagogía','Contactar', 'Julio Grondona');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-08-20', 'Jose Alberto Pastoriza', 'Salud física','Espera de respuesta', 'Julio Grondona');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-08-21', 'Carlos Mario Goyen Prieto', 'Salud mental','Contactar', 'Julio Grondona');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-08-21', 'Nombre Apellido', 'Motivo', 'Citax', 'Julio Grondon');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-09-01', 'Nombre Apellido', 'Motivo ', 'Citax', 'Julio Grondona');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador)
VALUES('2020-09-01', 'Nombre Apellido', 'Motivo ', 'Citax', 'Julio Grondona');









