CREATE TABLE IF NOT EXISTS seguimientos
(
    id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	fecha date NOT NULL,
    name text NOT NULL CHECK (name <> ''),
    motivo text NOT NULL CHECK (name <> ''),
	estado text NOT NULL CHECK (name <> ''),
	orientador text NOT NULL CHECK (name <> ''),
	color_estado text NOT NULL CHECK (name <> '')
);

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-08-15', 'Ricardo Enrique Bochini', 'Pedagogía', 'Citadx', 'Julio Grondona', 'rgba(86,204,242,0.7)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-08-15', 'Carlos Alberto Enrique', 'Salud Mental', 'En Proceso', 'Julio Grondona', 'rgba(39,174,96,0.7)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-08-16', 'Ricardo Omar Giusti', 'Discapacidad','Sin Estado', 'Julio Grondona', 'rgba(189,189,189,0.7)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-08-16', 'Claudio Oscar Marangoni', 'Re-orienacion vocacional','Citadx', 'Julio Grondona', 'rgba(86,204,242,0.7)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-08-20', 'Jorge Luis Burruchaga', 'Pedagogía','Contactar', 'Julio Grondona', 'rgba(242,201,76,0.7)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-08-20', 'Jose Alberto Pastoriza', 'Salud física','Espera de respuesta', 'Julio Grondona', 'rgba(235,87,87,0.7)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-08-21', 'Carlos Mario Goyen Prieto', 'Salud mental','Contactar', 'Julio Grondona', 'rgba(242,201,76,0.7)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-08-21', 'Nombre Apellido', 'Motivo', 'Citax', 'Julio Grondona', 'rgba(86,204,242,0.7)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-09-01', 'Nombre Apellido', 'Motivo ', 'Citax', 'Julio Grondona', 'rgba(189,189,189,1)');

INSERT INTO seguimientos (fecha, name, motivo, estado, orientador, color_estado)
VALUES('2020-09-01', 'Nombre Apellido', 'Motivo ', 'Citax', 'Julio Grondona', 'rgba(39,174,96,0.7)');









